### ISSUE TITLE
Having trouble running your sample even though the dll exists and using 

### ISSUE THREAD

**Issue by alanrose** [bertt/GdalOnNetCoreSample#2]
Having trouble running your sample even though the dll exists and using latest gdal from
http://www.gisinternals.com/release.php. See below
Any ideas

"Can't load requested DLL: C:\\Program Files\\GDAL\\gdalplugins\\gdal_netCDF.dll\n127: The specified procedure could not be found.\r\n"} | System.ApplicationException

**Comment by bertt** [comment]
Hi, can you try installing the GDAL tools from https://trac.osgeo.org/osgeo4w/ ?

**Comment by bertt** [comment]
I did an install on a clean Windows installation, got it working by:

- Install older (2.x) version of QGIS (http://download.osgeo.org/qgis/windows/QGIS-OSGeo4W-2.18.28-3-Setup-x86_64.exe). The more current 3.10 installation seems missing gcs.csv file.
- Set GDAL_DATA enviroment variable to directory where gcs.csv is installed (default C:\Program Files\QGIS 2.18\share\gdal)

There might be a way to get it working by installing only GDAL not QGIS complete.

**Comment by bertt** [comment]
Closing
