### ISSUE TITLE
PostgreSQL driver support 

### ISSUE THREAD

**Issue by 15213145749** [bertt/GdalOnNetCoreSample#3]
Hello, thank you for your project. I have encountered some problems when using it. I need to use PostgreSQL driver, but I don't support it at present. I hope you can add PostgreSQL driver when you are free, or give me some guidance on how to add PostgreSQL driver. Thank you

**Comment by bertt** [comment]
Hi, ok I’ll see if I can make a sample for this. As alternative you can also use Npgsql like https://github.com/bertt/wkx_dapper_sample

**Comment by bertt** [comment]
I've checked on this, but the PostgreSQL driver seems to be missing (both on Windows/Linux). There is another project (https://github.com/MaxRev-Dev) for GDAL 3.1, but PostgreSQL is also missing (PROJ6, SQLITE3, GEOS(3.8), HDF4, HDF5, GEOTIFF, JPEG, PNG, LIBZ, LERC, CURL).

So my conclusion: it's not possible to get from GDAL to PostgeSQL, NuGet GDAL package maintainers have to be contacted for this. Or use the Npgsql package directly (I expect thats also faster).

**Comment by 15213145749** [comment]
PostgreSQL Driver can get from NuGet GDAL.Navite package  but just on windows (dotnet framework).
I wanna running on linux ；I solved the problem with Npgsql

**Comment by bertt** [comment]
ok excellent
